### ISSUE TITLE
Map start button in Model2 to Dolphinbar mode 2

### ISSUE THREAD

**Issue by ckeisc** [argonlefou/DemulShooter#110]
I am using Demulshooter with Model2 emulator and 2 Wii mote + Dolphinbar running in mode 2.
Everything works as expected - trigger and reload are read correctly from the 2 mouses exposed by Dolphinbar.

My problem is the "start button". I have configured the game to be in free play mode, but I still need to map a start button for each player. Ideally, I would like to map a button that is on the Wii Mote, in Dolphinbar mode 2, the "+" button is hard coded to be keyboard Enter key.

My question is - can Demulshooter intercept the "+" button press to trigger 1p or 2p start in M2 emulator?
The two "+" buttons in the 2 Wii Mote are exposed as Enter keys from two different keyboard device, so apps supporting Raw Inputs (like MAME or Supermodel and Demulshooter) should be able to tell apart the two keys and then trigger corresponding start key for the right player. I did some search and can't find how to make this work. Please let me know if this could be achieved.

**Comment by argonlefou** [comment]
Did you try with Autohotkey to remap the Enter key to the desired button in the emulator ?
AHK is pretty powerfull, this may work

DemulShooter is not made to read data from multiple devices (for 1 player)
So if a wii mote is emulated as 2 differents devices (mouse for aiming and buttons, keyboard for other buttons) this would not work in the current state

**Comment by popo69200** [comment]
I think this video can help you
[https://www.youtube.com/watch?v=TJXRoTA0BLo](url)
Ginzu is a gun killer player

**Comment by ckeisc** [comment]
@popo69200 the video only worked around the problem by assigning P2 start to a different key ("2" in the case), so that the Enter key would only affect P1 but not P2. But the solution is incomplete because P2 cannot start playing with only WiiMote without having to reach for the keyboard for the "2" key.

I would look into AHK to see if AHK could intercept keys with multiple keyboard awareness and allow new key events to be translated and sent to the emulator.

**Comment by argonlefou** [comment]
I don't know if AHK can separate same key from different keyboards, I just know it is able to do it for different joystick...
That's why I was thinking that you caould have a look at it, as it's a powerfull tool and but just now the simplest basic functions of it

If not, I'm affraid that you'll have to find some specific program doing that kind of keyboard interception (based on hardware Hid ) and remap :(

Unfortunatelly, as far as DemulShooter is concerned, this is not possible to add this feature without a total rewrite of the core of the program...which is not doable at all today
