### ISSUE TITLE
Dolphin 4 lightguns

### ISSUE THREAD

**Issue by ProfgLX** [argonlefou/DemulShooter#121]
Could it be possible to have demulshooter work with 3 wiimotes in Dolphin stable version 5 instead of just 1? People are starting to have more lightguns and there are some great 4 player games on wii for it, but I don't know how much work that entails :)

As a side question, coud it be possible to update the hack to onw of the newer dolphin "unstables"? I'm sure that is much more work and understand if not feasible.

Thanks Argon

**Comment by argonlefou** [comment]
Hi,

On a general note, it's really hard to update DemulShooter for new "unstables" (or even "stables") build of a target : every single change in the emulator code means that the compiler will change the memory locations of the build executable.....and everything must be done agin from scratch
Looking at Dolphin "unsttable" releases, I can see at least a dozen for the past 2 days :-/

That's why, except for a few things like Flycast - where I'm just reading outputs without any memory hack, and where the emulator is so well done that it's outputing the needed address on it's log file - I always suggest people to ask the on-development emulator to change things natively. 
Again, flycast is an excellent exemple with a new builds few days ago supporting analog controlers for lightgun games.


On a specific note, and unfortunatelly for Dolphin, the hack I made is so "hacky" and such a weird thing to put on (with the whole crazy `-ddinumber` thing I did) that I don't think I would be able to maintain the code now that I haven't touched it since.....years (when I released it )
So updating the hack is impossible. Well, nothing **_is_** impossible but it would require a lot of time and headache pills 


The main issue with emulators is that I have 2 solutions to handle inputs with DemulShooter :  
- The first one is **_game-based-hacks_** : this is impossible with Dolphin if you even start counting every different games (and versions of each game)
- The second one is hacking the emulator controls on a general way. That's the -ddinumber hack purpose, but it's too compicated to change and update.

If something has to be done, it would be a full rewrite from scratch but I can't afford to spend time searching for some new better hack that can't be sure to even exist.
Same goes for going from 2 to 4 players....I don't even remember how I did the 2 players and I never touched it again since

So I'm not cloding the ticket because it's really a good request, but updating support for newest release is not doable on the current state
Updating to 4.....maybe doable or not, I don't know. But will stay on the very bottom of my real and virtual to-do-list

**Comment by ProfgLX** [comment]
Thanks for your reply and consideration Argon. I was afraid you'd say that, but completely understand. I've also asked Dolphin devs in their ticket system if they'd be interested in adding Raw input, which would probably fix everything without hacks.

**Comment by ProfgLX** [comment]
Hi Argon, if you want to close this issue (unless you want to keep it open), Dolphin 4 players is doable using joystick mode on lightguns that have it (Gun4IR and Sinden, don't know about the rest.

**Comment by argonlefou** [comment]
Oops, I may have skipped this !

Thanks for the tip, I'll close the ticket
