### ISSUE TITLE
Virtua Cop Gun4IR Player2 Trigger Issue

### ISSUE THREAD

**Issue by elgarlic** [argonlefou/DemulShooter#130]
Hi,
I'm having an issue running the latest demulshooter with model2 emulator and Virtua Cop. I'm using Gun4IR, and the player2 trigger seems to control Player1 trigger (only). Lightgun 2 tracks well in the service menu, but the input readings show trigger 2 as always "on", and again the second gun just fires the first gun's trigger button. Virtua Cop 2 and HOTD behave normally, and I haven't had a similar issue on any other platforms with demulshooter. 

I see someone else posted about the exact same problem on reddit but doesn't seem to have figured it out: https://www.reddit.com/r/Gun4IR/comments/10i5pmv/model_2_running_virtua_cop_with_demulshooter_bug/

**Comment by argonlefou** [comment]
I'll try again in a couple of weeks, I'm not able to untill then

**Comment by KiiinkyFoxx** [comment]
Hi
I was having same issue, only found out because I was being nosey and reading this.
I found changing
XInput=1 to XInput=0 in Emulator.ini solved the issue in the Test Menu
I also find loading Demulshooter after the emulator helped on this one - I know it shouldn't make a difference but in the past I had an issue and cannot remember which game it was with on this emulator but doing Demulshooter after stopped it - I have a feeling it was something to do with a gun trigger being on but it was a while ago and the memory is hazy- sorry
Cheers

**Comment by elgarlic** [comment]
> Hi I was having same issue, only found out because I was being nosey and reading this. I found changing XInput=1 to XInput=0 in Emulator.ini solved the issue in the Test Menu I also find loading Demulshooter after the emulator helped on this one - I know it shouldn't make a difference but in the past I had an issue and cannot remember which game it was with on this emulator but doing Demulshooter after stopped it - I have a feeling it was something to do with a gun trigger being on but it was a while ago and the memory is hazy- sorry Cheers Ps I am not using Gun4ir though - just something I noticed in case it helps

Ah, thanks very much! Xinput to =0 did the trick. Wasn't needed for the other games, but apparently was for vcop. I'm loading demulshooter first, as I had some issues with it causing a crash when loading after in my early tests (probably something I could have resolved).

**Comment by argonlefou** [comment]
Thanks for pointing that out !

I'll add a note about it in the Wiki !
