### ISSUE TITLE
Castlevania The Arcade Demulshooter Wiimote Problem A button

### ISSUE THREAD

**Issue by foxhidden2009** [argonlefou/DemulShooter#148]
Hello Argonlefou,

I'm facing a problem with Castlevania The Arcade. First of all thanks for your hard works and especially for making this game playable !

I play with a Wiimote, DolphinBar in mode 2 so wiimote is recognized as a mouse.
Following your wiki, buttons are assigned and hardcoded like this:

 [MouseLeft] -> Whip Yellow Button in-game (Wiimote B button)
 [MouseRight or MouseMiddle] -> Whip Red Button in-game (Wiimote A button) 

If I use your file "CastlevaniaArcade Input.exe" I can use A button without problems.
Now I want to Play in 2P mode with 2 Dolphins Bar in mode 2. 
So I use an ahk script witch DemulShooter v10.11.0 and launch the game with this line:

Run, "D:\Castlevania the arcade\Demulshooter.exe" -target=konami -rom=HCV

And with this setup Wiimote A button is not working anymore even with only 1 wiimote ! I don't understand why.

I have tried to change behaviour of A button of the wiimote with DemulShooter " Enable virtual mouse button" and assign a keyboard button to "middle mouse" Key. But after that I don't know assign to assign this keyboard key to the "A" button of my wiimote in my script for P1 and P2 because it says that a dupplicate value was found (A button cannot be listed twice which is logic)

in Fact: 
Run, "D:\Castlevania the arcade\Castlevania_Inputs.exe" ->  A button is working
Run, "D:\Castlevania the arcade\Demulshooter.exe" -target=konami -rom=HCV -> A button not working

Note: I have tested with Sinden Gun and I see with mapped button what is working or not:

"Castlevania_Inputs.exe" ->  [MouseRight or MouseMiddle] ->Working Both
"Demulshooter.exe" -target=konami -rom=HCV ->  [MouseRight] ->Not Working [MouseMiddle] ->Working
-> Seems that with DemulShooter only  [MouseMiddle] button is working and this button is not assigned to wiimote in mode 2 with Dolphin Bar !

Note: I have tested this setup on another computer, fresh wwindows 10 install and same problem occurs, button A not working.

I cannot use your "Castlevania_Inputs.exe" to play in 2P, support only 1P, that's why I'm searching a way to make it work with DS...

Thanks for your feedback !

**Comment by argonlefou** [comment]
> [MouseLeft] -> Whip Yellow Button in-game (Wiimote B button) [MouseRight or MouseMiddle] -> Whip Red Button in-game (Wiimote A button)

Hello !
This is a silly copy/paste error on the Wiki, I'll change it ASAP.

There is indeed only the middle button that can act as the Red Button (throw projectile) with demulshooter. The reason is simple : Right Button with guns is usually obtained by shooting off-screen.....which make impossible to aim at the screen to throw a projectile while shooting off screen at the same time


> I have tried to change behaviour of A button of the wiimote with DemulShooter " Enable virtual mouse button" and assign a keyboard button to "middle mouse" Key. But after that I don't know assign to assign this keyboard key to the "A" button of my wiimote in my script for P1 and P2 because it says that a dupplicate value was found (A button cannot be listed twice which is logic)

Welcome to the wonderfull world of multiple mice on Windows...
The idea is good, using a virtual button to simulate the input but - indeed - you must be able to map a button of your Wiimote to that key. I don't think you can do that if mode 2 is a simple mouse, as windows merge all mice commands to a single one device.


> "Castlevania_Inputs.exe" -> [MouseRight or MouseMiddle] ->Working Both "Demulshooter.exe" -target=konami -rom=HCV -> [MouseRight] ->Not Working [MouseMiddle] ->Working -> Seems that with DemulShooter only [MouseMiddle] button is working and this button is not assigned to wiimote in mode 2 with Dolphin Bar !

The `Castlevania_Inputs.exe` tool simply reads windows mouse cursor and buttons. That's why you can use Wiimote and right click while aiming at the screen, and that's why only 1 device can work

So, to make it short :  
If you want to use Wiimote in mode 2 with demulshooter, you will have to find a way to use/simulate middle click

You can also have a look at the recent #146 ticket : although still unconfirmed, you may be able to use the Wiimote in mode 4, (letting you choose buttons as you wish). But be sure to select the good axis to be able to get movements.
Use Ds_Diag to search for them in the device, based on the video posted, if it works in Ds_Diag it should work in DemulShooter too
