### ISSUE TITLE
Gun Calibration Off Set For TeknoParrot Games

### ISSUE THREAD

**Issue by kim-sama** [argonlefou/DemulShooter#15]
I updated TeknoParrot and games like Rambo and Let's Go Island messed up the gun calibration.I have UseMouseForGun unchecked for both games and I haven't changed the DemulShooter config
Here is video: https://drive.google.com/open?id=1mXf2AspMBgbgr1FtuilyQb-RXDSO0p5O

**Comment by argonlefou** [comment]
Just tested with this update: 
TeknoParrotUI - 1.0.0.292
OppenParrotWin32 - 1.0.0.175
OpenParrotx64 - 1.0.0.175
OpenSegaAPI - 1.0.0.124
TeknoParrot - 1.0.0.28

No offset seen on any game

**Comment by kim-sama** [comment]
Well, it works for Rambo now. But something happened to Lets Go Island. I downloaded and played Lets Go Island 3D with Demulshooter and it works good, then I played the normal Let's Go Island and the calibration is offset, I went to the test menu and fixed it (00h and ffH) but it still doesn't work

**Comment by argonlefou** [comment]
Ok, this might be normal :
Indeed, LGI native resolution is something like 1600x1200 (if I remember well) and there was patches to make it run in 1920x1080. Unfortunately - and this is the case for a lot of games - these patches are improving 3D rendering but totally screw up 2D rendering as all sprites are now stretched or placed in the wrong place
That being said, the cursor on screen are totally off, but the aim should be alligned with your gun

So for LGI :
- Playing in windowed mode you should have your aim + crosshair + shots all at the same spot
- If you can add a custom resolution to your GPU, add LGI resolution and play it fullscreen so that it can be stretched to fill but keep it's original resolution, you should have same results
- Playing it with 1080p mod : your aim and shots will be aligned , but you won't be able to use crosshair correctly

Finally, you can also apply the no-crosshair patch and play whatever mode you like or - that's what I did - forget this game and use LGI 3d : this is the very same game but with native 1080p support. And there is a mod to remove the "NO 3D" icon on top of screen

**Comment by kim-sama** [comment]
I guess my only choice is to play the 3D version for now on

**Comment by argonlefou** [comment]
That's what everyone is doing since it has been released. Don't forget that you can disable the 3D part in the SERVICE menu

**Comment by kim-sama** [comment]
It's turned off by default, if you don't mean removing the "3D OFF" texture

**Comment by argonlefou** [comment]
No no, the "3D OFF" texture is not a game setting
It has been a long time since I set it up and didn't remember that the default setting was 3D off
