### ISSUE TITLE
There is no output in Castlevania

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#151]
It will vibrate a little when it is first started, but there is no output during the game.
[Debug_2023-06-06_12-09-49.txt](https://github.com/argonlefou/DemulShooter/files/11659832/Debug_2023-06-06_12-09-49.txt)

**Comment by argonlefou** [comment]
Thanks for the debug file but unfortunately, as far as outputs are concerned this will not be enough because MameHooker comes in play, and also has a nice debug window with lot of informations in it.

What is not working ? 
What outputs are you expecting that are not working ? 
Are outputs registered in MameHooker windows ? 
Are the values changing in the MameHooker window?

Sorry for the reply but you just can't open a new issue every new game because you don't know how to make things work and yelling "there is a bug" without explaining at all what's going on

Now there is a very simple thing about your issue : Output work with Castlevania. That's a fact, and verified by a lot of people.
So it means the issue, whatever it is, is on your side.

Now please, you already mentionned using a Gun4IR to play : there is a discord channel with a lot of people (myself including) happy to help people set-up guns and game.

So that this place can stay clean with REAL bugs
