### ISSUE TITLE
Virus\false positive?

### ISSUE THREAD

**Issue by megrendel** [argonlefou/DemulShooter#154]
Downloaded v11 and Windows Defender shows it as having Trojan:Win32/Wacatac.H!ml. Previous version of 10.15 installed with no issue.

file: C:\Users\Arcade\LaunchBox\Emulators\DemulShooter_v11.0.zip->Unity/NightHunter/InputPlugin_Config.exe

**Comment by argonlefou** [comment]
Hi,

There were no code change at all between 10.15 and 11.0 regarding Night Hunter InputPlugin_Config.exe, so you can safely use the one from the 10.15 package if you feel safer with it.

Now, about the false positive : 
I've been searching on the web but didn't find any usefull information. Except that using online tools like Virustotal showed that even a simple "Hello World" empty app has Trojan warning from some antivirus

I don't really know why this is hapenning in this InputPlugin_Config.exe - which is pretty empty as an application - and not DemulShooter with all memory/process hooking stuff ??

Finally, as I can't rule out a contamination targetting the exe file from the computer I build these on, you can also build sources at home if you feel better

The only thing I'm certain of, is that the code itself has nothing to be feared of and that's one of the main reason I put the sources available here on github (so that people can verify if they are affraid)

To be continued....(and hopefully solved one day ?)
