### ISSUE TITLE
House of the Dead 2 and 3 PC version Player 2 won't work with Sinden Guns 

### ISSUE THREAD

**Issue by wild-child83** [argonlefou/DemulShooter#162]
In the past I used Aimtrak Guns but upgraded them for Sinden Guns which I like more and are more accurate. 
House of the Dead remake PC version works like a charm with the latest patch and Demulshooter. and many Teknoparrot and other Mame and Model 2 and Model 3 games. 

With my older Aimtrak guns Player 1 and 2 worked perfectly with an older version of Demulshooter that I used.  

But Unfortuantly Hotd 2 and 3 PC Version player 2 wont work with the Sinden Guns and i Used the latest Demulshooter build... 
Demulshooter recognize Player 2 partially as player 1... in Hotd you can shoot as player 1 with Player 2 gun and Hotd2 it just not recognize Player 2... I setup them both up as keyboard as instructed but that also does not work. And setting them up standard (1x mouse + 1x keyboard) it also wont work. 

My sinden guns works perfectly with HOTD Remake with Demulshooter so it's not my guns fault but an software issue!?
Have someone managed to set HOTD 2 and 3 up with 2 working players with Sinden guns and the latest Demulshooter?

**Comment by argonlefou** [comment]
Aimtrak, Sinden, Gun4IR, etc..... doesn't make any difference. If it's working with one, it will work with the other (on a DemulShooter point of view, so when a device is correctly configured on itself)

So, theorically yes, Hotd2 and hod3pc are working perfectly fine with Sinden, a lot of people used them on the Sinden DISCORD channel
I do not use them myself so I'm not the best to talk about them and how to properly make them work

Now there are more things in the chain than just "gun issue" or "software issue" : a game version can be unknown of demulshooter, some settings for Sinden or windows can be troublesole, etc....

First thing to do, in order to have a clearer view would be to provide DemulShooter log files for both games :  https://github.com/argonlefou/DemulShooter/wiki/Debugging

Hotd2 is usually easy to configure on computer.
Hotd3 looks like more troublesome for a lot of people, even if I never had any issue with it. You can also try this mod for Hod3PC (always with DemulShooter) to see if it 's working better (not saying to use this instead of the original game if you prefer the original better, but this can help to debug) :  
https://github.com/argonlefou/Hotd3pc_ArcadeMod

**Comment by argonlefou** [comment]
> I am really not kidding with the Aimtrak both games work fine in the past with an older version of demulshooter with those 2x same versions of HOTD pc that i used. 

Never said you were kidding, but I know for sure that Aimtrak and Sinden are outputing exactly the same kind of values, so it the same for DemulShooter.
If the Sinden is outputing correct values, of course

> But I do play now both games in windowed mode (for Sinden) and do not use re-shade (fixed white border) with those games but I guess that doesn't matter?.... 

Windowed mode ? No, this could only impact axis accuracy but for those 2 games windowed mode is perfectly supported (that's how I run the games to develop)
But for the white border, I don't know anything about it so it's up to you

> also when I choose both players keyboard mode with Sinden the player 1 controls also don't work well in the menu selection screen of HOTD while if you choose mouse + Keyboard control it does work fine. 

That kind of symptom is typical of DemulShooter not interracting with the game.
So not correctly configured, not hooked to exe or broken in a update.

> The Dpad for instance won't work when I choose both players keyboard of the SInden gun.

I don't know what DPad is doing with Sinden so, I kind of don't care
Only interresting info would be axis, and mouse buttons (on and off screen)

> I now use a different version of demulshooter as a few months ago that i Used for my aimtrak guns (those worked for years perfectly with your software on HOTD 2 and 3). I will provide some log files.

Yes please. Because even if I can have ideas by reading some descriptions, only the log file can provide me some precise info to start rulling out issues.

And please do not start to bring Model2 or whatever other game behaviour to compare and make some wrong conclusions, there is no use in that..
Sinden needs per game setup because of the borders so stick to the game and move on to another once it's done.

**Comment by wild-child83** [comment]
OK THANKS FOR THE HOTH3 ARCADE MOD AND ALSO THE  TEXTURE PATCH that you can download to improve the graphics! The game looks even better now and more arcade like too. And weird enough now both guns also works GREAT!!? When I choose Keyboard both and choose the arcade launcher.exe. So that is been solved!! Now to see if I can fix HOTD2 ass well and let you know.

**Comment by wild-child83** [comment]
Fixed HOTD2 as well. Deleted the game completely and used an new DUMP and now it worked fine. SOrry for the trouble but atleast I got upgraded HOTD 3 now thanks to your info! Keep up the good work buddy!
