### ISSUE TITLE
Support for Operation Wolf Returns?

### ISSUE THREAD

**Issue by jadflat** [argonlefou/DemulShooter#165]
This game aims very poorly with Sindens in its current state, it's basically unplayable. Would love to see it supported.

Love your work and thank you

**Comment by Rocamoyas** [comment]
Yes please Argonlefou! Make the dreams reality !!!!

**Comment by argonlefou** [comment]
At first sight, the game input handling is hell to change.
They are mixing a lot of stuff with VR support 

Not sure something can be done, and if it is.....it's a long shot


As for messages containing illegal download files, they will be deleted here.

**Comment by jadflat** [comment]
Thanks for looking into it

**Comment by Plaasvark** [comment]
Dammit!!!! I was just looking around for a fix to this issue. Someone mentioned DemulShooter might be the answer to make the mouse input Raw.. Hopefully the developers can patch the game..

**Comment by argonlefou** [comment]
Solo and multiplayer Input support added on release v11.2, as well as outputs
Wiki updated with needed informations : https://github.com/argonlefou/DemulShooter/wiki/Windows-games#operation-wolf-returns

**Comment by Aynshe** [comment]
Hi,

I have two Gun4IRs, the "in game and for both players" pointer remains locked in the lower left corner, however it works perfectly in the menu and I can select without seeing the windows cursor.


I tried to load DemulShooterX64.exe -target=windows -rom=opwolfr before or after in vain.
The light turns green.

I also have Output mode enabled because I already use demulshooter/mamehook for demul/flycast, TP and compatible Windows games and it works fine.

;)

[Debug_2024-01-01_03-25-39.txt](https://github.com/argonlefou/DemulShooter/files/13802598/Debug_2024-01-01_03-25-39.txt)




_(for information, I wrote scripts (far from being professional and perfect) for ES under retrobat (discord retrobat available) in order to automate the loading of demulshooter/mamehook for compatible emulators (flycast and demul basically) integrated into retrobat including teknoparrot and compatible windows games.)_.

**Comment by Zorgonaute84** [comment]
Hello,

Thanks for the job, it work very well. But, is it necessary to force the button allocation ? Specially the change weapon and reload ? It could be so nice to let the user specify the buttons.

Thanks and happy new year

**Comment by argonlefou** [comment]
Yes it is, unfortunately.
Because  DemulShooter, as it was created 10+ years ago had no support for custom key mapping.

You can still add custom keys by mapping other buttons to keyboard keys and enabling virtual buttons for yout lightgun
