### ISSUE TITLE
Elevator Action Death Parade and Teknoparrot

### ISSUE THREAD

**Issue by Styx78** [argonlefou/DemulShooter#166]
Hello,
I would like to use DemulShooter with teknopparot but I can't do it.
I use teknoparrot with "attratcion Doors" Enable
I don't use the game.exe included with JConfig.exe because it doesn't work with teknoparrot.
The crc of my game.exe is BBDFE625

my problem is :
Whilst DemulShooter and Teknoparrot works, the aiming is offset along the x axis and shakes a lot when you get closer to the edges.
I have no problem if I use teknoparrot alone.
in-game calibration doesn't change anything

Thanks for your help

**Comment by argonlefou** [comment]
Hi,
Just to be sure to understand :
Are you trying to run DemulShooter to handle inputs while running the game with Teknoparrot ?

Or are you using DemulShooter to get outputs while the game is running and controled by Teknoparrot ?

**Comment by Styx78** [comment]
I try to run DemulShooter to handle game inputs while running the game with Teknoparrot.
With teknoparrot alone I cannot use off-screen reload

**Comment by argonlefou** [comment]
Thanks for the details.

You won't be able to use DemulShooter to handle game inputs with Teknoparrot.
DemulShooter will only work with clean game dump.

Jconfig was released a bit after so I didn't try with it but I don't think it would work.

So : either you use TP and TP input system, or clean game dump as a Standalone with DemulShooter

I'll update the wiki to add these details
TP and JConfig were not supporting the game when I wrote it

**Comment by Styx78** [comment]
I have trouble telling the difference. I thought DemuShooter was used to manage inputs, regardless of whether we use Teknoparrot, Jconfig or GameLoader. THANKS

**Comment by argonlefou** [comment]
No, you're mixing software that are not doing the same thing at all.
- Jconfig comes with a modded exe per game, to be able to emulate the I/O board (usuallly JVS)
- Teknoparrot does....things that only the devs know about and sometimes needs specific modded exe too. Sometimes it's an emulator, sometimes it's some king of wrapper to run games that can be run alone and do not need any loader.
- GameLoader is just compiled script to act on the graphics/display/cheats. It does not emulate anything
- DemulShooter hooks the running exe to inject data in memory so that your device can control the game. As a consequence, different versions of a same game needs different DemulShooter code, that's why how the game is run (and with what binary) is important.
DemulShooter Wiki usually specifies which version are supported

Teknoparrot added it's own RawInput control code a few years ago, making it possible to use multiple lightguns for games. 
DemulShooter was not needed anymore for games emulated under Teknoparrot, so input support is no more updated for TP (old code still existing and may work for old TP emulated games, but there will be no update).
If you have issue with how TP is handling controls with a specific game, you need to ask them to change things.

For this Elevator Action, updated DemulShooter to  hook the game before TP added any support to it.
So only the clean game running standalone (without TP) can be controled by DemulShooter.
Running it with TP would obsiously change hi the binary behave, thus breaking compatibility with DS
Same thing goes for Jconfig for this game, released afterward with a modified exe.

So you have to choose to run the game :
- Tp only
- Jconfig only
- Standalone exe + Demulshooter

On top of that, DemulShooter can handle outputs to feed recoil, rumble or LED.
This usually can be used with any loader (TP, Jconfig, Etc...) as I'm just reading values and hacking the code is not necessary

**Comment by Styx78** [comment]
Many thanks for your explanations. I understand better now. I think these explanations will help a lot of people.

**Comment by carolis15** [comment]
I'm having the same problem as the OP, but I´m using DS just for Outputs and TP for everything else. But if I run the game with DS the aiming is off in the X axis. There is no diffrence if I use the -noinput command

**Comment by argonlefou** [comment]
There is absolutely no reason for DS to act on Axis values if the -noinput switch is properly used. 
This switch even prevent DS from writing values to the game's memory

You can still join a debug file
