### ISSUE TITLE
ringwide > og P2 virtual mouse buttons affect P2 middle button

### ISSUE THREAD

**Issue by miguelmmm** [argonlefou/DemulShooter#17]
Running DemulShooter_v8.7.0 as Admin
DemulShooter.exe -target=ringwide -rom=og
Current behavior:
P1 works OK but all 3 P2 virtual mouse buttons also trigger P1 middle button.
Expected behavior:
P1 and P2 virtual mouse buttons work independently.

Below is the relevant section of the config.ini
;Player1 Device configuration
P1Device = XInput Gamepad #1
P1GamepadLeftClick = 8192
P1GamepadRightClick = 4096
P1GamepadMiddleClick = 256
P1GamepadStick = L
P1GamepadVibrationEnabled = 0
P1GamepadVibrationLength = 50
P1GamepadVibrationStrength = 0

;Player2 Device configuration
P2Device = XInput Gamepad #2
P2GamepadLeftClick = 8192
P2GamepadRightClick = 4096
P2GamepadMiddleClick = 256
P2GamepadStick = L
P2GamepadVibrationEnabled = 0
P2GamepadVibrationLength = 50
P2GamepadVibrationStrength = 0

**Comment by argonlefou** [comment]
Hello,

> P1 works OK but all 3 P2 virtual mouse buttons also trigger P1 middle button.

I have trouble to understand your issue, as they are only 2 Virtual Mouse Buttons that can be enabled by player, and they are only used with a mouse device, not XInput device

**Comment by miguelmmm** [comment]
Hi, thanks for the quick feedback. After some browsing I found a version v8.8.2 in the arcadecontrols forum and that fixed it.
I used the wrong name, I meant Game Pad Buttons, not virtual mouse buttons.
The issue was that the P2 Game Pad Buttons for Mouse Left, Middle and Right also triggered P1 Middle (Weapon change). So every time that P2 pushed any button, P1 would change weapon.
As I mentioned, I tried v8.8.2 and no longer see this.
Are those newer versions available here in Github as well?
Thank you!

**Comment by argonlefou** [comment]
You're welcome.
I usually release binaries on arcadecontrols forum - which is the main source of information because all started here - and then here, with the new source code.

I didn't push the last update because I made it quick and dirty for the unexpected release of Friction.
I have been working on a whole rework of the software for a few weeks now and I'd rather focus on it than on the current version, and I don't want to push bad ugly code along with a new release here.

That beeing said, I'm surprised the 8.8.x version solved your issue as the only difference between 8.7.x and 8.8.x is the added support of Friction dump

**Comment by teeceds** [comment]
I'm having the same kind of issue with house of the dead 3. 2 aimtraks set up working pretty good, except for the fact that player two trigger button also shoots player one at the same time. Been killing myself over it haha. Any ideas? Using the latest version of demulshooter, aimtrak utility configured the same for both aimtraks, both selected as "use virtual mouse buttons" P1 z,C,x and P2 a,s,q. 

Thanks in advance
