### ISSUE TITLE
RingWide > og crosshairs not reaching sides when in fullscreen

### ISSUE THREAD

**Issue by miguelmmm** [argonlefou/DemulShooter#18]
Tried following the RingWide Wiki for OG
https://github.com/argonlefou/DemulShooter/wiki/RingWide
At the bottom it states "You can then run the game (gs2.exe) as a standalone or with GameLoaderAllRH to get it fullscreen."
When I try that, crosshairs no longer reach the sides, they reach the top but not the left and right sides. In game calibration doesn't make a difference.
Versions:
DemulShooter_v8.7.0
EmuCR Game Loader All RH 364

**Comment by argonlefou** [comment]
Hello,
I just tried with Game Loader All RH 365 with these settings and everything was working as planned :
[Settings.zip](https://github.com/argonlefou/DemulShooter/files/4473958/Settings.zip)

Note 1 : 1366x768 is my laptop resolution
Note 2 : I stopped using this loader a long time ago (even if it's real good at doing what it does) because it was messiing badly with demulshooter at that time, and moreover I don't like apps changing my personnal computers parameters (display, sound, graphical settings) without asking

**Comment by miguelmmm** [comment]
Hi, tank you very much for the help!
After further troubleshooting with your settings and resolution I decided to try an actual Xbox gamepad.
The Xbox gamepad reaches top, right, bottom, and left and doesn't reach the corners which is normal per the rounded nature of he stick. Demulshooter works as expected (mirrors what I see in Windows > Game Controllers > Test).
What I'm trying to figure out now is why with the virtual gamepads generated by Touchmote, Demulshooter don't reach the left and right sides.
Windows > Game Controllers > Test show that those virtual gamepads reach everywhere, even the corners (unlike actual Xbox gamepads).
In this case Demulshooter doesn't mirror what I see in the gamepad test.
I'll keep troubleshooting Touchmote, if there is any info that can be of help, I'd be happy to provide.
Thanks again!

**Comment by argonlefou** [comment]
This may not easy to debug....
The first question I'd ask would be, does your issue only happen with Operation Ghost or also with any other game/emulator ?

**Comment by miguelmmm** [comment]
I came across a beautiful piece of code "DsDiag_v2.0.exe" in the forum ;) and realized that the virtual Gamepad generated by Touchmote doesn't reach the absolute values of the axis (0x0000 and 0xFFFF). See snapshots below.
Seems like windows is trimming those values and that's why Joy.cpl shows it reaching all corners but the actual values don't reach the limits.
Not sure how that works but it seems like Demulshooter does not consider the "Windows Calibratrion" or trimming of the joysticks but the RAW values only.
Is there any way to trim/calibrate Demulshooter? I tried doing in-game calibration but that didn't work.

![Real Xbox Controller Left](https://user-images.githubusercontent.com/30830577/79257768-1d2e0b00-7e58-11ea-8a77-929f323995c4.png)
![Touchmote Right](https://user-images.githubusercontent.com/30830577/79257774-1e5f3800-7e58-11ea-8459-b84b5e89ac90.png)
![Touchmote Top](https://user-images.githubusercontent.com/30830577/79257776-1ef7ce80-7e58-11ea-9ebc-403d8b320baa.png)
![Touchmote Left](https://user-images.githubusercontent.com/30830577/79257777-1ef7ce80-7e58-11ea-819d-1d3321a05a88.png)
![Touchmote Bottom](https://user-images.githubusercontent.com/30830577/79257779-1ef7ce80-7e58-11ea-8cd5-cf0ffa999d98.png)

**Comment by argonlefou** [comment]
That would have been my 2nd question, to use Ds_Diagv2.0 and see what happens ;)
Before I can say anything, could you generate a device report (upper right button : export device data) and share it with me here ?

As for calibration, no it is not possible : DemulShooter goes between the game and the device driver.
Calibration must be done before. The only thing that is possible (in the GUI, Act Labs tab) is to add a fixed offset to correct old gun that couldn't be calibrated at all and were always "too much on the left" or similar

I'd say your issue is more of a "range" problem and adding a fixed amount of offset won't help you

I've no Wiimote/TouchMote to test myself but a lot of people managed to use them without this range issue

**Comment by miguelmmm** [comment]
Hi thanks for the feedback,
I'm attaching 4 DS_Diag exports:
[DsDiag_Report_2020-04-15_12-56-21 (Touchmote P1).txt](https://github.com/argonlefou/DemulShooter/files/4482681/DsDiag_Report_2020-04-15_12-56-21.Touchmote.P1.txt)
[DsDiag_Report_2020-04-15_12-55-51 (Touchmote P2).txt](https://github.com/argonlefou/DemulShooter/files/4482680/DsDiag_Report_2020-04-15_12-55-51.Touchmote.P2.txt)
These are the ones I get when I connect the 2 Wiimotes using Touchmote and assign the IR sensor as as the joystick.
The problem here is as you said calibration/range. Touchmote does not use the whole range for the X-Axis so it seems that I would need to trim/reduce both sides. I think I saw someone calling this negative deadzone. I am able to calibrate this out in windows (Joy.cpl) but it seems that the actual raw value stays the same and that's what causes Demulshooter to not reach the sides.

An alternative I was trying now was to use the Dolphin bar natively in mode 3 (without Touchmote) where it assigns the IR to 2 axes.
DS_Diag shows the crosshair reaching everywhere OK as soon as I select the device but for some reason DemulShooter doesn't show those controllers in the Device dropdown.
I noticed Joy.cpl shows the IR axes as Z Axis / Z Rotation, not as X/Y. Maybe that has something to do with that. See snapshot.
![DsDiag and Joy cpl (Native Dolphin bar mode 3 P1)](https://user-images.githubusercontent.com/30830577/79367584-1ec10700-7f1c-11ea-80e1-588ae4bd6c4c.PNG)
 
[DsDiag_Report_2020-04-15_13-02-16 (Native Dolphin Bar mode 3 P2).txt](https://github.com/argonlefou/DemulShooter/files/4482679/DsDiag_Report_2020-04-15_13-02-16.Native.Dolphin.Bar.mode.3.P2.txt)

[DsDiag_Report_2020-04-15_13-00-57 (Native Dolphin bar mode 3 P1).txt](https://github.com/argonlefou/DemulShooter/files/4482682/DsDiag_Report_2020-04-15_13-00-57.Native.Dolphin.bar.mode.3.P1.txt)

**Comment by argonlefou** [comment]
Thanks for the repports, I can confirm that in "Touchmote Mode" you should be able to obtain 0x0000 -> 0xFFFF on every axis (but I don't know how to set this with Touchmote)
And you're right, DemulShooter receives raw values that are generated by TouchMote, so calibrating in Joy.cpl wouln't solve the problem

As for "Mode 3" dolphin bar :
DsDiag 2.0 is part of the new version of demul I'm working on and the main reason of this update is a totally new core to handle gamepad/joystick/Hid devices, and this will include Xinput (real or virtual) devices too in a different (and better ?) way than the build-in Xinput support I'm currently using
The current Demul can't handle wiimote like that and that's why you couldn't see your device on in the device list of any demulshooter binary available.
In the new version (that I hope to finish in couple of few weeks max) you'll be able to use your Wiimote in mode3 just with the very same behavior you get in DsDiag 2.0

As for Axis X,Y, Z or whatever name it has on windows is not important
What's important is the range of value you get (and the behavior of the axis) when you select one of them in the drop down list to affect to X or Y (in DsDiag)
For example 0x39 will certainly be the D-Pad of your wiimotes and does not output analog values but simple 1-3-5-7 values

**Comment by miguelmmm** [comment]
These are great news. I wish you luck in the development and I'll be in the lookout for that new version. If you need some testing, I'd be happy to help.
