### ISSUE TITLE
HOTD Remake (Steam) can´t start Player2

### ISSUE THREAD

**Issue by Jack77777777** [argonlefou/DemulShooter#185]
Hi @argonlefou 

I am using Demulshooter 11.4 and HotdRemake_ArcadePlugin v2.0.
Both configured for multiplayer. But both Guns start only Player1.
Tried with Demulshooter 11.3. before. Reinstalled HOTD Remake 3 times with deleteing left over folder after uninstall.

I use the Sinden Lightguns, They are configured right, i can use them both simultanous in teknoparrot games.

Thank you in advance

**Comment by Jack77777777** [comment]
Here is the log:
[Debug_2023-12-11_09-15-10.txt](https://github.com/argonlefou/DemulShooter/files/13632684/Debug_2023-12-11_09-15-10.txt)

**Comment by argonlefou** [comment]
Hello,

Your debug file shows that you're using a known version of the game and, nothing relevant regarding a bad configuration.
DemulShooter is finding the game windows and process.

There are no known bugs with DemulShooter 11.4 + Remake mod (both are working together as it should)

So this is an issue regarding the mod install/usage or the whole package (DemulShooter + Mod + Sindens) install/usage/configuration.

For that I have to close the ticket (because this is not the place for it) and highly advise you to seek help on Sinden Discord channels. People there will be able to help you for that

**Comment by Jack77777777** [comment]
I got help in the Sinden Discord. I had configured "1" as start button for both guns in the Sinden software. Changing to "2" for Gun2 fixed it.

**Comment by argonlefou** [comment]
Thanks for the feedback
