### ISSUE TITLE
DemulShooter with TeknoParrot for Akuma

### ISSUE THREAD

**Issue by EmuAl** [argonlefou/DemulShooter#207]
This isn't an issue as such just more of a question.
I'm having problems running Akuma on TP, everything works except the trigger.
I can run Akuma with Demulshooter but can't have the crosshairs and bezel that TP allows.
When I run both TP (to load the game) and Demulshooter (for inputs) the trigger is the only thing that works.
My question is, is it possible to run both together so I can get all the inputs and the crosshairs and bezel.
Is there a proper way to run both programs together ?
thanks for any help you can give with this problem

**Comment by argonlefou** [comment]
Hi,

TP has it's own input system and it's own loader to control the game.
For that reason you won't be able to use DemulShooter to control the game started with TP, mainly because it would be first necessary to find and block current inputs in order to put mine....

So if you want to stick with TP, you'll have to seek help on their side in order to find out if the  trigger issue comes from their loader or you configuration

If you want to stick with DemulShooter, there are easy ways to add bezels with ReShade and some pluggins. I do it that way (as well as fixing some games display ratio on screen)
As for crosshairs....I don't know if it's possible in the current state : reshade plugin would need to get coordinates data from DemulShooter to draw the crosshair at the good spot.

Note that you can still use DemulShooter with TP games to get output data, as it has no interference with the input system.

**Comment by EmuAl** [comment]
thanks for the reply dude, i suspect its problem on my end, was just hoping you had an answer.
when i use demul it is perfect just can't see where i am shooting with the wiimote gun thing
anyway thanks for your time and help
