### ISSUE TITLE
Possible virus when downloading DemulShooter v12.5

### ISSUE THREAD

**Issue by faluki1983** [argonlefou/DemulShooter#213]
When I downloaded DemulShooter v12.5, it detected it as a virus, but the DemulShooter v12.4 version did not.

**Comment by argonlefou** [comment]
Maybe a possible issue like #154 ....

I tried various different online file scanner and they all give the same results with 12.5 or 12.4.
But all antivirus do not agree on their respective results for a same file......

As I said in the past, I'm not surprises of the false positive, as Demulshooter heavily relies on mechanics affecting other process and their memory .
That's why the code is public, so that anyone can compile it itself or check for malware if they are suspicious

**Comment by argonlefou** [comment]
is it still happening with the v12.6 ?
