### ISSUE TITLE
I can't find rpcs3gun.exe

### ISSUE THREAD

**Issue by Dark14543** [argonlefou/DemulShooter#219]
I don't understand how to do it but I couldn't find rpcs3gun.exe. Does it come when I download it or do I need to do something else?

**Comment by argonlefou** [comment]
rpcs3gun.exe is part of a special build of RPCS3 emulator, targetting arcade games.
It's not part of DemulShooter and you won't find it in DemulShooter zip package.

As for where to find it, best option is Google with `RPCS3` and `SYSTEM 357`
You won't find it on official RPCS3 github because of Licensing issue
