### ISSUE TITLE
Wartran Troopers Pedal System

### ISSUE THREAD

**Issue by dante3732** [argonlefou/DemulShooter#234]
Add please pedal system in Wartran Troopers.
There you need to move the cursor out of screen, like in gundam zeon

**Comment by argonlefou** [comment]
Wartran is running thanks to TP, there is no input support from DemulShooter so no way to change inputs mode to create a pedal mode or similar.

I had kind of a standalone launcher many years ago, but the game crashed at gameplay time because of directx/screen rendering (surely because of the way the game is designed to appear, multi screen) and this is not my zone of expertise.
