### ISSUE TITLE
Suggestion: The player's start button can be set freely,

### ISSUE THREAD

**Issue by cmjdbb** [argonlefou/DemulShooter#236]
Hi argonlefou, I have a suggestion: can the player's start button be set freely, so that the start button can be set to any button on the light gun, for example, the trigger button is set to start, so that there is no need to go to the keyboard to press 1 and 2, after the game is over, directly pull the trigger to start again.

**Comment by argonlefou** [comment]
Hi

Thanks for the suggestion.
However, on most of the game, DemulShooter is not handling the start button and sonthere is no option to set it to anything

DemulShooter, on it's core, was not created as an emulator with buttons assignment for each game
Only a lightgun "patch" to shoot and reload (which is why some games like Gundam had me map all in-game actions on gun buttons)

There are some exceptions though, when I had to make launcher to run game that have no other way to run

So in the end, to go into your suggestion, I'd have to turn DemulShooter into a TP clone with per-profile game configuration, full button configuration

This is not the plan at the moment
