### ISSUE TITLE
Reload Crashes

### ISSUE THREAD

**Issue by carolis15** [argonlefou/DemulShooter#246]
Hi, RELOAD crashes with DS Ver. 12.11 when loading missions. With earlier version of DS the missions load fine
[Debug_2024-08-16_12-16-37.txt](https://github.com/user-attachments/files/16640428/Debug_2024-08-16_12-16-37.txt)

**Comment by argonlefou** [comment]
Hi
I have listed 3 different versions of the game binary, but I unfortunatelly kept only one of them

You have one of the 2 others and - unfortunatelly for you - DS crash the game because it does not have the corresponding memory values for the latest changes.

I'd be gratefull if you could mail me and share just your exe file, so that I can update it's memory config file

**Comment by argonlefou** [comment]
Should be fixed in v13.0 update
