### ISSUE TITLE
Rpsc3 (Rising Storm) question for analog gus?

### ISSUE THREAD

**Issue by Prime91122** [argonlefou/DemulShooter#256]
Hello Argon, First of all thank you for all that you do. I was hoping, can Demulshooter help me map my analog guns to play Rising Storm with (RPSC3)  just the basic functions, I understand the outputs like recoil is not possible due to it being a console game and not an arcade version. I'm just trying to play the game with the analog guns. Hoping for a script that will allow Demulshooter to hook the game. Thank you

**Comment by argonlefou** [comment]
Hello,

As a side note, outputs are not imposible because of the fact that the game are console instead of arcade (I added outputs to some PC games, and a forked version of PCSX2 can add recoil to some games) but because the emulation process of the PS3 code makes it very very very hard to have access to game data and code in order to recreate outputs.

That being said, as far as inputs are concerned, there's nothing demulshooter will be able to help you for for many reasons.

Prime reason is the fact that support would be broken as soon as RPCS3 release a new build.....which is....very often 

What was possible for a specific and unique arcade release won't be for regular releases updated many times a week.
