### ISSUE TITLE
Please add option to use middle mouse button for either cycle weapon or throw grenade in Operation Wolf Returns

### ISSUE THREAD

**Issue by judegreer** [argonlefou/DemulShooter#265]
Right now, middle mouse seems to be hard-coded to cycle weapon.  Would like to see option to use it for either cycle weapon or throw grenade

**Comment by argonlefou** [comment]
Hello,

Demulshooter is lacking per-game buttons configuration because it was absolutely not designed to be some sort of launcher/emulator (like TeknoParrot can be) when it was first created.

There are a couple of games with that feature in DemulShooter_GUI but they absolutely needed control support at that time, and would not have worked without custom key mapping.

It's not in my plan to add that whole layer of game-input configuration, because of the time it would need to develop the GUI and the heavy changes it would require in the core of the program.

Even though I totally agree that it would be a nice thing to do, as well as pointing to the game executable for each target so that DS can launch programs and patch them before runtime instead of doing hard-patch from the GUI.
But, if you add those 2 features to DS, you'll get .....TeknoParrot ^^

So, I'm sorry but with that current limitation of DS I can't afford to change buttons each time someone asks me to (and it's not rare)
Even though I'm not satisfied with that kind of answer, unfortunatelly.

If I have to re-work the program in the future, full input configuration would be the first thing to do.

**Comment by judegreer** [comment]
Understood, thank you for the thorough explanation
