### ISSUE TITLE
Aimtrak trigger P2 effects trigger P1

### ISSUE THREAD

**Issue by teeceds** [argonlefou/DemulShooter#27]
I'm having the same kind of issue as another person with house of the dead 3. 2 aimtraks set up working pretty good, except for the fact that player two trigger button also shoots player one at the same time. Been killing myself over it haha. Any ideas? Using the latest version of demulshooter, aimtrak utility configured the same for both aimtraks, both selected as "use virtual mouse buttons" P1 z,C,x and P2 a,s,q.

Thanks in advance

**Comment by argonlefou** [comment]
Hi,
First, running demulshooter by adding a _**-v**_ command and sharing the debug.txt file created in DemulShooter's folder may provide some helpfull information.

Then, especially for HOD3 where DemulShooter is sending virtual keyboard inputs for trigger and reload, you have to be carrfull so that any "virtual mouse button" you set in demulshooter are not messing with HOD3 keys configured in the game's menu

**Comment by teeceds** [comment]
Thanks for the reply mate. Yeah looks like the virtual mouse buttons are the same as some of hotd3 Controller buttons. I'll map reload and trigger for both player 1 and 2 in hotd3 game to alternate keys and see how I go. That seems like the easiest option. Right now player 1 trigger in game is "z" and player 2 is "n". Maybe it's the z that causing conflicting issues

Thanks again
