### ISSUE TITLE
no Chihiro cfg files

### ISSUE THREAD

**Issue by bigcam79** [argonlefou/DemulShooter#33]
im trying to run virtua cop 3. i followed the tutorial but when I execute the ahk it tells me it can't load Chihiro when I look into the memory files of demulshooter there no folder for Chihiro or cfg file for vcop3. i get this error.

![Capture](https://user-images.githubusercontent.com/73762348/98456939-20ac1b00-2137-11eb-8c9c-b56db8d3f5cd.PNG)

this is the script I'm running I have no idea whats wrong
Run, c:\cxbx\Cxbx.exe /load c:\cxbx\vc3.xbe, c:\cxbx
Sleep 5000
send,{AltDown}{Enter}{AltUp}
Sleep 5000
Run, c:\DemulShooter\DemulShooter.exe -target=chihiro -rom=vcop3, c:\demulshooter

**Comment by argonlefou** [comment]
This is an AHK error message, so it's AHK crashing because of a file not found.
I'd say, looking at your screenshot, that you have no _**c:\DemulShooter**_ folder on your drive as we can clearly see that there's only a folder named _**demul shooter**_ on your C drive.
A correct path on your AHK script should make things better.

And, for information, if any mandatory DemulShooter related file was missing, you'd have a DemulShooter error message instead of AHK error message
