### ISSUE TITLE
[REQUEST] Crosshair 

### ISSUE THREAD

**Issue by BroKill** [argonlefou/DemulShooter#35]
Hello Argon,

thank you so much for this great app, Demulshooter!

I have a request as the title said ( if possibile).
Can you add the ability to display a crosshair that moves with the peripheral?

Since I play with gamepad Naomi shooter games, a crosshair would help a lot to play it in a better way.

If you can't add It to Demulshooter directly, can you make a separate one?

I apologize if this post is not related to Demulshooter issues but I don't know how to contact you for asking this.

Thanks for your support and thanks in advance for my request.

Best regards

**Comment by argonlefou** [comment]
Hello,

Unfortunatelly this is not something I can do, because this would mean having access to the video rendering of each game to add a drawing or a texture for a crosshair. 
You can't simply add a drawing inside a game's window without this

The only exception is Model2 Emulator, because it's scripting system allows any user to add .lua scripts and access video/memory/game data before each frame rendering

**Comment by BroKill** [comment]
I've Imagine that.

Thanks for your reply.


Best regards
