### ISSUE TITLE
Any way to make DemulShooter pcsx2 compatible?

### ISSUE THREAD

**Issue by jesmartinez** [argonlefou/DemulShooter#36]
Hello, I have been trying to find some valid configuration for some years to be able to configure nuvee (pcsx2 & 3) with two wiimotes to play with 2 players.
But nuvee only supports wii controllers through DirectInput, so it's impossible.

Demulshooter is much better, it is a great software that behaves much better with the wiimote. Is there any way to do some kind of compilation that it works in pcsx2?

Maybe using part of the nuvee open source code?

Thanks for all, and sorry if I bother.

**Comment by argonlefou** [comment]
Hello,

This won't be possible for a lot of different reasons :
- DemulShooter is hooking a process memory to modify it and change axis/button data directly. Nuvee is a standalone plugin, which is loaded by the emulator and is emulating a guncon device (i.e this is not some hack, this is real emulation : transmission protocol, etc...)

- To use DemulShooter (as it is working now) with PCSX2, this would mean to search and hack each and every game separatly.  And each different .iso - PAL, NTSC, etc... - of a same game would also need it's proper hack. This would need hundreds of hours.
You can see how nuvee settings have to be changed for each game (calibration and screen data)

- A new update of PCSX2 (and there are a lot of them) may break DemulShooter compatibility at any time (remember, DemulShooter is only a hack, not a device emulator)

The best solution would be to use part of Nuvee source code and part of DemulShooter source code (and both program are not using the same language) to create a new GunCon emulator plugin working with WiiMotes and etc....
But I won't be that man, mainly because I can't afford to spend sooo many hours to do that and, on top of that, I'm not using any WiiMote at all (and Nuvee is working perfectly fine with Aimtrak)
