### ISSUE TITLE
Operation Ghost 2nd player cannot reload

### ISSUE THREAD

**Issue by ProfgLX** [argonlefou/DemulShooter#41]
First thank you for your great program.

The 2nd player in operation ghost cannot reload when shooting offscreen or using the button corresponding to reload. Player 1 works flawless.

Thank you :)

**Comment by ProfgLX** [comment]
Fixed by using Demulshooter, gameloader rh AND teknoparrot all at the same time. Didn't work when teknoparrot wasn't involved. One thing I've noticed is that player 2 has a slight offset to the bottom left of where you're pointing. Player 1 is spot on.

**Comment by argonlefou** [comment]
Hello,
There are many different ways ways to run O.G so let's try to find some answers (knowing that I'm talking about the game beeing run direclty without any other soft on top of it, like TP or Game Loader)
Using Teknoparrot may enable 2nd player even if Demulshooter is running correclty but I don't know how offset may be handled.

1 - Without DemulShooter running, Player 2 controls are on the keyboard Numpad. Make sure that NumPad5 is shooting and NumPad0 is reloading.
2 - If this is working with the numpad, try again with DemulShooter. This should work as DemulShooter is only sending virtual keypresss event to the game

If reloading is still not working, run DemulShooter by adding the **-v** option, this will create a debug.txt in DemulShooter's folder that you can share here. This may help to find something wrong.

**Comment by ProfgLX** [comment]
For some reason, I can't load the game without at least Game Loader all rh. Demulshooter works great with it, no offset at all.

It's really only the reload of player 2. NumPad0 works, but out of screen from the gun itself does not. It works for player 1, both guns have the exact same settings. I think I know what's happening, player 2 out of screen sends another command through demulshooter to the game, the action button which is used to scan.

Sorry to have taken so much time to answer !

[debug.txt](https://github.com/argonlefou/DemulShooter/files/6370550/debug.txt)

**Comment by argonlefou** [comment]
Thanks for the reply, and no worries for the delay, I'm not always quick to answer myself

> 
> 
> For some reason, I can't load the game without at least Game Loader all rh. Demulshooter works great with it, no offset at all.
> 
Looking at the debug file, you're using a version of the game that should run fine without TP or GL, as long as there is no change in the binary (resolution patch) and as long a the FULLSCREEN setting is not enabled in the game config file.
Changing the resolution or using fullscreen _**may**_ work but it will be hardware dependant. Usually GL is a quick fix for this, but this should not have any effect on Demulshooter anyways

>
>
> It's really only the reload of player 2. NumPad0 works, but out of screen from the gun itself does not. It works for player 1, both guns have the exact same settings. I think I know what's happening, player 2 out of screen sends another command through demulshooter to the game, the action button which is used to scan.  

Ok, so the fact that the action button is simulated is a good thing : as explained on the wiki (https://github.com/argonlefou/DemulShooter/wiki/RingWide#controls-) the right mouse buttons is mapped to both reload and action.
So your siden button is detected as it shoud be

But, looking back at the code, I did not mapped the button press for reload, but a screen position of the cursor (reloading happens when the aim reaches the border of the screen, which obviously happens when you're going off-screen.
I think I can remember why :  
- For P1, the game is reloading when the cursor reaches the screen border, so with a right mouse bouton click I'm forcing an X values off screen to force the game reload
- For P2, I'm looking at the lightgun position to send the NumPad_0 input, even if no button is pressed so it should reload when you're just pointing out of the screen

I can see that your cursor is going to the border and should trigger the reload but apparently it does not work and I'm not sure I can tell why (is this a Sinden issue because this is handlng the out of screen differently ?)

But I can try to change the P2 handling to reload with a button without looking at the coordinates if you want to try ?
I'm not sure why I did it that way, but there should be a reason (even if I forgot :p )

**Comment by ProfgLX** [comment]
Thanks for the reply! The exact same thing happened when I played with aimtraks a couple months ago, so I don't think it's specifically the Sinden's fault. Of course I'd be willing to try anything you need and assist in the squashing of this "bug" :)

**Comment by argonlefou** [comment]
So, I ran some tests at home and Aimtraks are working as expected for Player 2 :
- Reloading when reaching screen borders
- Reloading when using right click event (at the same time as action button is simulated)

You can try this DemulShooter attached with the _**-v**_ option and share the debug file again. 
There is nothing new in the code from the last release, but a couple of new debug lines to be sure that the reload button is send to the game.
[DemulShooter.zip](https://github.com/argonlefou/DemulShooter/files/6389909/DemulShooter.zip)

According to the debug file, the problem may be more on the OS/hardware side preventing the simulated keypress to be sent to the game, but it looks like other buttons (shoot, change weapon and action button) are working great so this is weird

**Comment by codeener** [comment]
Hi Argonlefou, thank you for your work. I have a strange occurrence in Operation Ghost on Player 2 only when I point my Gun4IR onto the screen after moving it off the screen, a black border shows up on the screen for a moment. Perhaps this is related to the reloading off screen. Not sure if it's related to demulshooter. I am using Game Loader since I cannot get TP to work with this game.

**Comment by argonlefou** [comment]
Demulshooter isn't acting with graphics in any way.

To find the issue, it's better to run run Operation Ghost without Game Loader, this  software has been known to cause compatibility issue with Demulshooter and some other things.

You don't need TP to run the game. If the fullscreen is not working well, the 1st solution is to add a cutom resolution corresponding to the game in your windows display settings (1024*600)

Or, you can also use DgVoodoo 2 : use d3d9.dll and set "DefaultEnumeratedResolution = None" and "ExtraEnumeratedResolution = 1024x600" in dgvoodoo.conf

But this is not really a place for display setting advice

**Comment by ProfgLX** [comment]
Wanted to report that testing with v10.9.6, everything works as intended, so this can be closed.
