### ISSUE TITLE
Support for Rambo The Video Game - Baker Team

### ISSUE THREAD

**Issue by gustavoalara** [argonlefou/DemulShooter#43]
Hi!

Could you add support for Rambo The Video Game - Baker Team. It is a similar game to Heavy Fire Afganistan and works the same way. I've tried to add it myself, but I'm afraid I don't know how to find the correct memory offsets to map the X,Y coordinates and buttons. (Maybe a help guide on this for adding new games and collaborating with you could be useful too).

Thanks in advanced

**Comment by argonlefou** [comment]
This is not an option for now.
The game may have similar playstyle, that doesn't mean it's sharing the same code engine.
Un that particular case, I remember it beeing a mess to hack (i.e more like blue estate)

there is no way to make some "help guide" as every game has it's own specificity, and finding X,Y data is  the easiest part of the process. The hardest part is to find where and how to properly block the game code refreshing these values, so that it won't override Demulshooter's one
