### ISSUE TITLE
Pressing the down arrow key when one player is active crashes DemulShooter

### ISSUE THREAD

**Issue by RavenMacDaddy** [argonlefou/DemulShooter#51]
Things are about to get weird and very detailed, so I'll try to make things easier through this list: 

- Wii remote is connected to the Mayflash DolphinBar running in Mode 2.
- This makes the connected Nunchuck's analog stick correspond to the arrow keys on the keyboard.
- All the data is delivered through RAW devices, one for mouse, one for keyboard - keyboard obviously involved with the mentioned Nunchuck analog stick.
- Pressing up, left, or right works - but as soon as you press down on the analog stick, the hooked application stops responding to the device, easily visible since the corresponding crosshair is then stuck in place.
- Here's where it gets tricky... connecting two Wii remotes, both with Nunchucks, each connected to their own Mayflash DolphinBar in Mode 2, playing a game through an application that's hooked by DemulShooter - essentially the same setup but with two controllers instead of one - pressing down on the Nunchuck's analog stick on any of the controllers DOESN'T make the hooked application stop responding to the controls.
- Any other applications, whether they use RAW or not - significantly not being hooked by DemulShooter - never has any problems when using one Wii remote + Nunchuck in the mentioned configuration and pressing down on the analog stick. You can even see it continue to work as expected/normal by testing the same actions in the DsDiag app. This is only an issue in hooked apps.

So, some thoughts with the above in mind:

Logically, since DemulShooter only makes use of one RAW device, the one you select, I would expect the issue to be the same with either one or multiple Wii remote + Nunchuck controllers, but apparently this isn't the case. 

The logical reasoning being: first I play as expected, using the IR sensor to aim and using the corresponding controls for left and right mouse click, but as soon as I start using the RAW keyboard device through the analog stick, DemulShooter would get confused - but with multiple controllers/players active, this doesn't happen.

Whatever the app does when two players are configured and active essentially needs to happen also when a single player is.

Tell me if you need more data, and thank you for your time.

**Comment by argonlefou** [comment]
I'm not sure to understand everything but let's try :

So the Nunchuk is seen as a RAW keyboard device ?
If that's the case, I don't know how you can see it work as expected in DsDiag because DemulShooter is not using RawInput data from keyboards.....only mouse and HID devices.

About the issue when putting the Nunchuk analock stick to the down position : it would be great to know if the game doesn't respond anymore because DemulShooter crashed and closed itself, or because DemulShooter is still running/blocked/unresponsive and doesn't feed the game like it should.
AND, if DemulShooter is still running (but not moving the crosshairs), does it still closes itself when the game is closed ?

If you want to post more files, you can run DsDiag, select your WiiMote and click the upper right button to generate a device repport text file. You can do it twice, one with and without the Nunchuk

Also, by using only one WiiMote, you can run DemulShooter with the _**-v**_ option added in the command line and play the game until the bug happen. Then you can share the debug.txt file (will be created in DemulShooter's folder)

**Comment by RavenMacDaddy** [comment]
> So the Nunchuk is seen as a RAW keyboard device ? If that's the case, I don't know how you can see it work as expected in DsDiag because DemulShooter is not using RawInput data from keyboards.....only mouse and HID devices. So I'm curious to know how the Nunchuk behave and what are DsDiag info on screen

Well, let's try to sort it out.

The DolphinBar as a device sends two RAW devices to the computer, one for keyboard and one for mouse - that's in the mentioned Mode 2.

How they're used is pretty simple; any input that's sent from the Wiimote or the Nunchuck (which becomes an extension of the controller) that corresponds to a keyboard press is sent through the RAW keyboard device - and vice versa.

See below, taken from the manual, what the controls are: 

![image](https://user-images.githubusercontent.com/67732686/141520039-6f5504ed-65e4-4ed1-824e-3000f86f6f5f.png)

Now, what you just described makes total sense, because if I configure virtual mouse buttons, specifically the middle mouse button which isn't intuitively accessible, if at all, I set it to down on the analog stick, and it's successfully bound to the corresponding Down arrow key.

If DemulShooter was exclusively responding to the specified RAW device, this wouldn't work, as can be confirmed by configuring Flycast through RAW devices - namely, I set up my RAW mouse device from the DolphinBar, but if I use the analog stick to configure Start or the Middle mouse button it doesn't work, cause I'm configuring the RAW mouse device, not the RAW keyboard device.

If I actually go to configure the RAW keyboard device in Flycast, it communicates exclusively with those inputs, as expected.

> About the issue when putting the Nunchuk analock stick to the down position : it would be great to know if the game doesn't respond anymore because DemulShooter crashed and closed itself, or because DemulShooter is still running/blocked/unresponsive and doesn't feed the game like it should. AND, if DemulShooter is still running (but not moving the crosshairs), does it still closes itself when the game is closed ?

Pressing the down arrow key does indeed crash DemulShooter.

Since the analog stick is simply sending the corresponding input of the keyboard I thought I would try to actually press the physical down arrow key, and sure enough, it crashes DemulShooter - even when the Wiiremote is disconnected completely.

Next I tried with two Wiimotes and Nunchucks as mentioned before, since this had miraculously just worked for some reason at least previously.

Sure enough, I can press down on any analog stick, and I can press down on the actual keyboard, and DemulShooter stays alive and well.

> If you want to post more files, you can run DsDiag, select your WiiMote and click the upper right button to generate a device repport text file. You can do it twice, one with and without the Nunchuk

[DsDiag_Report_2021-11-12_20-24-19 - Wiimote+Nunchuck.txt](https://github.com/argonlefou/DemulShooter/files/7529915/DsDiag_Report_2021-11-12_20-24-19.-.Wiimote%2BNunchuck.txt)

[DsDiag_Report_2021-11-12_20-25-04 - Wiimote only.txt](https://github.com/argonlefou/DemulShooter/files/7529916/DsDiag_Report_2021-11-12_20-25-04.-.Wiimote.only.txt)

**Comment by argonlefou** [comment]
Ok, let's clean this a little and skip the whole "theorical" RAW device explanation from mayflash as well as Flycast configuration. this will only lead to confusion with how Demulshooter is working.

From now on, I'll speak from DemulShooter point of view : 
-Wiimote are detected as mice, with absolute coordinate and raw input support (just like any other lightgun, aimtrak, etc...)
When you're using the Wiimote, axis and buttons data are handled directly by Demulshooter with the RawInput protocol.
Theorically, from what you wrote : so far, so good !

-Nunchuck analog stick are basically seen as keyboard keys (maybe from another device than regular keyboard but for now I can't test this) and are not part of the device configuration :
"VirtualButton" options, in DemulShooter device configuration, is OS dependant : DemulShooter will not acces devices to get data but will use Windows low-level keyboard events. 
Which means that any Keyboard-alike device will be able to generate those buttons events.
Which also means that 2 Nunchuk will generate the same unique KeyPress event (exemple : Down Arrow) for ecery player (again, when using DemulShooter)
To make it simple : those buttons were initially created for people using arcade cabinet with devices like IPAC/APAC+ arcade buttons. That's why DemulShooter is not listening to a specific hardware device to get keyboard keys because there is -  usually, - one and only one device.

Now, this does not explain why DemulShooter closes itself when you press the Down button on your keyboard....
This, however, can explain why this is reacting differently with 2 players (the input beeing shared by all players)

Could you share your demulshooter's config.ini file ? (with both devices set to your wiimotes and virtual buttons set to Nunchuck stick directions)

Then I'll ask another set of debug files, but using the debug release of demulshooter I'm joining here : 
[DemulShooter_debug.zip](https://github.com/argonlefou/DemulShooter/files/7531776/DemulShooter_debug.zip)
If you can make some different files by using Nunchunk stick and keyboard "Down" key (please wait for the game to be hooked correctly before crashing demulshooter, otherwise log may not be complete)

You can also try to deactivate virtual buttons in DemulShooter GUI and tell me if the bug is still present like this.

**Comment by RavenMacDaddy** [comment]
> Could you share your demulshooter's config.ini file ? (with both devices set to your wiimotes and virtual buttons set to Nunchuck stick directions)

[config.txt](https://github.com/argonlefou/DemulShooter/files/7531796/config.txt)

I noticed that the Down arrow key is actually bound to Numpad 2, but it's the same thing with Up etc.

The same key is also bound (confirmed in the config.ini) whether I use my physical keyboard or the Nunchuck analog stick, hence it's confirmed that the Nunchuck is simply sending the corresponding keystrokes, not creating any X or Y axis analog inputs.

> Then I'll ask another set of debug files, but using the debug release of demulshooter I'm joining here : [DemulShooter_debug.zip](https://github.com/argonlefou/DemulShooter/files/7531776/DemulShooter_debug.zip) If you can make some different files by using Nunchunk stick and keyboard "Down" key (please wait for the game to be hooked correctly before crashing demulshooter, otherwise log may not be complete)
> 
> You can also try to deactivate virtual buttons in DemulShooter GUI and tell me if the bug is still present like this.
> 
> Note that this debug version is also correcting a Typo in DemuShooterGUI device configuration, where virtualbuttons label where not correct (twice Middle buttons)

This is something I forgot to mention, I did try to run with Virtual keys disabled even before creating this issue and got the same result.

Give me a moment and I'll fetch the data anyway with the debug build.

**Comment by argonlefou** [comment]
The debug build has nothing more than a few more lines for Keboard Event debugging, compared to latest 10.4.0 build.

DemulShooter v10.3.0 is mentionned in your first debug log, and some details had to be changed (regarding keyboard handling and options naming in the config file) with this 10.3.0 update. 
This was mentionned on a few places on the internet but not in the text changelog in the package : but upgrading from v10.2.0 to v10.3.0 without removing/recreating the setting file can cause similar issues (because of the different options naming convention)

I let you close the ticket if you're considrering the problem solved !
At least I found a typo in the GUI thanks to you :)

**Comment by RavenMacDaddy** [comment]
You're correct about the issue, I'll do a clean install for future versions just in case.

Appreciate your help and the great project - it's truly a joy as a light gun game enthusiast, so thank you.
