### ISSUE TITLE
The House of the Dead 3 (PC) - Player 1 can't reload

### ISSUE THREAD

**Issue by Ronald-Diemicke** [argonlefou/DemulShooter#55]
So - it's  possible this is just me - but when configuring HOTD3 PC and using Sinden Lightguns, if I turn off the auto reload, the player 1 can't reload. This seems to be due to that the 1st player can't have their cursor go off-screen to reload.

Can someone reproduce this issue, or is it just me?

**Comment by argonlefou** [comment]
Which DemulShooter version is beeing used ?
Is the game correctly configured ?

I'll need a debug file from demulshooter, run it by adding the _**-v**_ option in the command line, run the game and move/shoot/reload in game.
Close everything and share the debug file created in DemulShooter's folder

**Comment by Ronald-Diemicke** [comment]
Which DemulShooter version is beeing used ?
10.4.1

Is the game correctly configured?
Think so.

Debug file:
[Debug_2021-12-08_10-57-05.txt](https://github.com/argonlefou/DemulShooter/files/7677658/Debug_2021-12-08_10-57-05.txt)

**Comment by argonlefou** [comment]
> 10:57:05.784864 : MD5 hash of C:\Games\HOTD3\exe\hod3pc.exe = 2659acf6fd763c7d918ea363d65ce7d5
10:57:05.784864 : /!\ MD5 Hash unknown, DemulShooter may not work correctly with this target /!\

I don't know Github policy about Copyrighted Material, so it would be safer to put it somewhere on a file sharing platform and send me a mail with the link

**Comment by Ronald-Diemicke** [comment]
Just sent you an email with the EXEs - I think  I know why this is happening though... I followed instructions here:
HOTD 3: https://www.wsgf.org/dr/house-dead-iii/en 
HOTD 2: https://www.wsgf.org/dr/house-dead-2/en

in order to fix the aspect ratios and resolution... I'm guessing anyone who did the same might have the same issues - especially if they did slightly different modifications... I know also that these games get modifications for the nocd patches as well... so I'm wondering if  you need to store all  the hashes or if there's also a way to 'force' the app to apply the modifications even if the hash  doesn't match... just a thought... I know you're  doing direct memory accessing so you could always put a YMMV disclaimer...

**Comment by argonlefou** [comment]
> Just sent you an email with the EXEs - I think I know why this is happening though... I followed instructions here: HOTD 3: https://www.wsgf.org/dr/house-dead-iii/en HOTD 2: https://www.wsgf.org/dr/house-dead-2/en
> 
> in order to fix the aspect ratios and resolution... I'm guessing anyone who did the same might have the same issues - especially if they did slightly different modifications... I know also that these games get modifications for the nocd patches as well... so I'm wondering if you need to store all the hashes or if there's also a way to 'force' the app to apply the modifications even if the hash doesn't match... just a thought... I know you're doing direct memory accessing so you could always put a YMMV disclaimer...

MD5 check in DemulShooter is just a warning, and the hack is still executed wether or not the MD5 is known.
The problem is: the memory location of the procedures to hack are changing in some of these different exe, that's the purpose of the .cfg files in DemulShooter's MemoryData folder.

By not finding a corresponding .cfg file, the most commonly encountered hack is hardcoded in DemulShooter and applied by default. It might work, or not, according to what kind of hack your exe need.

I tried your hod3pc.exe and it worked fine, the default hack is the good one and is correctly working.

Here are some things you can do to narrow down the faulty part :  
- Use unpatched exe
- Enable and set virtual buttons in DemulShooterGUI setting for your sinden
- Run demulshooter and the game as simply as possible (no frontend, no complicated scripts)
- **_Make sure you run DemulShooter as Admin_**
- During the game, try to shoot & reload with your sinden . Does it work ?
- During the game, try to shoot & reload with correspondingvirtual keys . Does it work ?



> Here's the specific changes I did:
> 
>     1. Aspect Ratio Fix:
>        Replace all instances of AB AA AA 3F with 39 8E E3 3F for 16:9 aspect ratio.
> 
>     2. Resolution Fix:
>        640x480 ==> **80 02** 00 00 C7 86 04 01 00 00 **E0 01**
>        to
>        1920x1080 ==>  **80 07** 00 00 C7 86 04 01 00 00 **80 07**

As a side note, touching the ratio/size of the window will mess with the line of sight and create offsets on the sides.

Instead of having distortion and misplacing on 2D sprites, my prefered way is to force the display on a 4/3 viewport at the center of the screen with a bezel around it (and keep the exe untouched). I'll share my file for testing purpose :

- Use DgVoodoo to enhance resolution (with d3d8.dll), and in the general tab set API output to Direct3d11
- Use Reshade to dynamically change the screen ratio as you want. Just unzip [ReShade.zip](https://github.com/argonlefou/DemulShooter/files/7692333/ReShade.zip) in your game folder and press [Home] keyboard key in game to acces the menu. Press [PageUp] / [PageDown] outside of the menu to swap presets.
- There's an option in DemulShooter that you can use to set things right and re-align the aim with the changed display, it's -forceXratio=4/3

Note that I couldn't get the aim aligned with your patched exe, in that case you may have to play with the -forceXratio setting to try to find a good value (-forceXratio=1.2, -forceXratio=5/4, etc.....)

**Comment by Ronald-Diemicke** [comment]
Think this was user error on my part; I think I missed that player 1 and 2 were supposed to use the keyboard option. I re-installed the game, fixed the keyboard option, DgVoodoo  and  ReShade  for the border and now this seems  to be working!
