### ISSUE TITLE
The House of the Dead 2 (PC) - Player 2 can't reload

### ISSUE THREAD

**Issue by Ronald-Diemicke** [argonlefou/DemulShooter#56]
Ironically - I just created an issue about HOTD3, but I'm also trying HOTD2 and funny enough - player 2 can't reload in this one...

Anyone else having this issue?

**Comment by argonlefou** [comment]
Same answer as fot your Hod3 ticket :  

Which DemulShooter version is beeing used ?
Is the game correctly configured ?

To have some clues about the issue beeing DemulShooter or your Sinden config, I'll need a debug file from demulshooter:
Run it by adding the -v option in the command line, run the game and move/shoot/reload in game.
Close everything and share the debug file created in DemulShooter's folder

**Comment by Ronald-Diemicke** [comment]
Which DemulShooter version is being used ?
10.4.1

Is the game correctly configured ?
I think so...

Debug file:
[Debug_2021-12-08_10-46-15.txt](https://github.com/argonlefou/DemulShooter/files/7677615/Debug_2021-12-08_10-46-15.txt)

**Comment by argonlefou** [comment]
> 10:46:15.768849 : MD5 hash of C:\Games\HOTD2\Hod2.exe = 3ce5b5c02839e99d6edd2ee862afccf1
10:46:15.768849 : /!\ MD5 Hash unknown, DemulShooter may not work correctly with this target /!\
I'd need to have a look at your game's executable to see if it can work with current hack, before searhcing for anything else

I don't know Github policy about Copyrighted Material, so it would be safer to put it somewhere on a file sharing platform and send me a mail with the link

**Comment by Ronald-Diemicke** [comment]
Just sent you an email with the EXEs - I think  I know why this is happening though... I followed instructions here:
HOTD 3: https://www.wsgf.org/dr/house-dead-iii/en 
HOTD 2: https://www.wsgf.org/dr/house-dead-2/en

in order to fix the aspect ratios and resolution... I'm guessing anyone who did the same might have the same issues - especially if they did slightly different modifications... I know also that these games get modifications for the nocd patches as well... so I'm wondering if  you need to store all  the hashes or if there's also a way to 'force' the app to apply the modifications even if the hash  doesn't match... just a thought... I know you're  doing direct memory accessing so you could always put a YMMV disclaimer...

**Comment by Ronald-Diemicke** [comment]
Here's the specific changes:
Aspect Ratio Fix (16:9):
Change all  instances of AB AA AA 3F to 39 8E E3 3F

Also using DgVoodoo2 to fix the resolution... but I don't think that'd effect this?

**Comment by argonlefou** [comment]
> in order to fix the aspect ratios and resolution... I'm guessing anyone who did the same might have the same issues - especially if they did slightly different modifications... I know also that these games get modifications for the nocd patches as well... so I'm wondering if you need to store all the hashes or if there's also a way to 'force' the app to apply the modifications even if the hash doesn't match... just a thought... I know you're doing direct memory accessing so you could always put a YMMV disclaimer...

MD5 check in DemulShooter is just a warning, and the hack is still executed wether or not the MD5 is known.
The problem is:  the memory location of the procedures to hack are changing in some of these different exe, that's the purpose of the .cfg files in DemulShooter's MemoryData folder.

Not knowing the MD5, and not finding a corresponding .cfg file, the most commonly encountered hack is hardcoded in DemulShooter and applied by default. It might work, or not, according to what kind of hack your exe need.

**In your case**, the default hack is the good one and your issue pointed out a copy/paste typo in DemulShooter's code where the P2 reload keys was set to P1 reload key.
This will be updated on the next release, and I can give you a workaround untill then :  
Unzip [3CE5B5C02839E99D6EDD2EE862AFCCF1.cfg.zip](https://github.com/argonlefou/DemulShooter/files/7692257/3CE5B5C02839E99D6EDD2EE862AFCCF1.cfg.zip) in DemulShooter's /MemoryData/windows/hod2pc sub directory
This will force DemulShooter to load this file and use the good keys (change the filename according to the MD5 hash of your exe if you're patching it again)


> Here's the specific changes: Aspect Ratio Fix (16:9): Change all instances of AB AA AA 3F to 39 8E E3 3F
> 
> Also using DgVoodoo2 to fix the resolution... but I don't think that'd effect this?

As a side note, enhancing graphics with DgVoodoo as no effect at all on the hack itself, but touching the ratio/size of the window (beiing hardcoded into the exe or with DgVoodoo strecthing options) will mess with the line of sight and create offsets on the sides.

Instead of having distortion  and misplacing on 2D sprites, my prefered way is to force the display on a 4/3 viewport at the center of the screen with a bezel around it (and keep the exe untouched). I'll share my file for testing purpose : 
- Use DgVoodoo to enhance resolution, and in the general tab set  API output to Direct3d11
- Use Reshade to dynamically change the screen ratio as you want. Just unzip 
[ReShade.zip](https://github.com/argonlefou/DemulShooter/files/7692270/ReShade.zip)
 in your game folder and press [Home] keyboard key in game to acces the menu. Press [PageUp] / [PageDown] outside of the menu to swap presets.
- There's an option in DemulShooter that you can use to set things right and re-align the aim with the changed display, it's _**-forceXratio=4/3**_  

Note that I couldn't get the aim aligned with the patched exe, in that case you have to play with the **_-forceXratio_** setting to try to find a good value (-forceXratio=1.2, -forceXratio=5/4, etc.....)

**Comment by Ronald-Diemicke** [comment]
Thanks for the fix. Can confirm this is working!
