### ISSUE TITLE
 Play HOTD with analog controller instead of mouse in M2 emulator

### ISSUE THREAD

**Issue by LeCarle** [argonlefou/DemulShooter#58]
I configured the program to recognize my analog controller and use the Lunchbox front end to start with Demuleshooter. But the Sega M2 emulator still uses the mouse. Please help.

**Comment by argonlefou** [comment]
If the emulator is still using the mouse, then DemulShooter is either not running or has not correctly hooked the emulator.

You won't find support for Launchbox configuration here, that's why I'm closing the ticket.

You can still check if there is some hardware issue with your analog controller : 
1) Run model2 emulator (and use correct compatble version). You can let it windowed
2)Run DemulShooter directly with the correct command line for the game you want to try
3)In your notification tray, you'll see Demulshootet's icon. 
3a) If the icon is red, it is not hooked to the emulator and you're doing it wrong
4b) If the icon is green, your gamepad should work

If 4b) and not working gamepad, restart the procedure by adding a _**-v**_ at the end of demulshooter's command line and share the debug file created in demulshooter's folder

**Comment by LeCarle** [comment]
Thank you very much for answering. I just realized that the demulshooter never opened as I don't see it in the notification tray.
