### ISSUE TITLE
Wild West Shoot Out PC + Demulshooter v10.7.1 - 2 player game - Random shots fired from opposite player's gun

### ISSUE THREAD

**Issue by markviv** [argonlefou/DemulShooter#76]
When playing a 2 player game using 2 Sinden lightguns if either player 1 or player 2 lightgun is fired rapidly while the other player is not shooting their's. Then the opposite players gun will once in a while fire a random shot even though the othe player not firing their gun.

Easily reproducible!

**Comment by argonlefou** [comment]
Not having 2 sinden to test, here's an idea to rule out some things :
1)unplug p2 sinden
2)run the game for 1p (with only 1 sinden software instance) with Demulshooter
3) in game test menu, diszble freeplay
3)add p1 credits to start and p2 credits so that p2 automatically enter the game (without having to shoot to enter like in freeplay mode)
4) does this behavior is still present within these conditions ?

**Comment by markviv** [comment]
There is no problem. Great work!

I reinstalled everything from the start. P1 and P2 Sinden lightguns both work at the same time without problems. Demulshooter is awesome!

**Comment by argonlefou** [comment]
Thanks for the feedback !
