### ISSUE TITLE
demul07_280418 + Demulshooter 10.7.1  - Naomi 2 Sinden Lightguns - Player 1 auto reload problem on some games 

### ISSUE THREAD

**Issue by markviv** [argonlefou/DemulShooter#79]
demul07_280418 + Demulshooter 10.7.1  With 2 Sinden Lightguns

Death Crimson OX - Naomi- Player1 auto-reload after every shot fired, Player Working normal
Confidential Mission - Naomi - Player 1 auto-reloads once Player 2 is out of bullets, Player 2 auto-reloads once player 1 is out of bullets
Extreme Hunting - Atomiswave - Player1 & Player2 working
Extreme Hunting 2 - Atomiswave - Player1 & Player2 working
House of the Dead 2 - Naomi- Player1 auto-reload after every shot fired, Player Working normal
Lupin the Third: The Shooting - Naomi- Player1 auto-reload after every shot fired, Player Working normal
Ninja Assault - Naomi- Player1 & Player2 working
Sega Clay Challege _Atomiswave - Player1 & Player2 working
Sports Shooting USA - Atomiswave - Player1 & Player2 working

**Comment by markviv** [comment]
![Sinden Player 1 Lightgun Button Assignment Settings](https://user-images.githubusercontent.com/33333645/168415573-b1da4253-d60d-483e-b091-cc4f469fb996.png)
![Demulshooter P1 Settings](https://user-images.githubusercontent.com/33333645/168415577-29ff98c0-848c-4275-9887-b0b2651f4709.png)
![Demulshooter P2 Settings](https://user-images.githubusercontent.com/33333645/168415578-365c5d64-ccef-4bb7-9aad-eed52a8c10b1.png)
![Sinden Player 2 Lightgun Button Assignment Settings](https://user-images.githubusercontent.com/33333645/168415579-a2c8a42e-ad8b-4a84-90f1-28951c03a6d0.png)

**Comment by argonlefou** [comment]
Hello,
I ran some tests with : 
- 2 aimtraks
- 2 Gamepads
- 1 Sinden
- 1 sinden + 1 aimtrak
-  Aimtrak + Gamepad

And I was never able to reproduce any of these auto-reload issue

ISo DemulShooter is working as it should, but I do not own 2 Sinden to try and I'm not a big Sinden user ( i.e : I'm not a pro to debug Sinden setups/soft issues) but I'd point you to try different simple sinden configuration to see if the issue is comming from Sinden buttons (unwanted pumps or right click events)
