### ISSUE TITLE
Add wiki note to Wild West Shootout

### ISSUE THREAD

**Issue by AckerApple** [argonlefou/DemulShooter#88]
I believe an additional note should be added to `Misc. Notes` of [Wild West Shootout](https://github.com/argonlefou/DemulShooter/wiki/Coastal#misc-notes). The note should be something like:

```md
- If game runs with black bars, aka 4:3 aspect ratio, and the gun appears to shoot higher than where you aim:
  - Chances are high, that you already have the very popular app `Borderless Gaming` and if not download/install it.
  - Open the WWS game using DemulShooter script and black bars should **still** be there
  - Then open `Borderless Gaming` (it opens into task bar) and on its left menu select WWS and tap the on screen **right arrow** icon
  - WWS may now already be in a fixed state and if not then on the right sided menu area, find “Cowboy” and edit it’s options to refine and perfect.
  - Ensure Borderless Gaming is set to startup with Windows so game always opens correctly
```

**Comment by argonlefou** [comment]
The wiki must be updated because I corrected a few issues mentionned in the misc notes (demulshooter can be run before or after without issue now), but why would anyone need to use 'Borderless Gaming' ?

Game resolution can be changed in the registry editor.

It may be dependant on hardware but I never had to run it with black bars (i.e 4/3 display on a 16/9 screen)

**Comment by AckerApple** [comment]
I changed the registry keys and it still did not work. I rebooted and was very confident of my changes.

Please consider adding section title of something like `If you still cannot get full screen correctly then other have reported the following to work:`

**Comment by argonlefou** [comment]
Did you try the [Launcher](https://www.mediafire.com/file/jaduzy6m1ba91i3/Wild_West_Shootout_Loader_v5.7z/file) available on [https://sindenlightgun.miraheze.org/wiki/WWS](Sinden Wiki webpage) ? 

The thing is, I have no intention to handle any Screen/Resolution/Setup issue that can exist with people messing with ReShade, DgVoodoo, DxWnd or Borderless Gaming.
DemulShooter is able to run fine with WWS on windowed or fullscreen. That's it.

Now, on the over hand, if an offset can be caused with certain conditions (4/3 display on a 16/9 screen can be one of them), there are tools ready in demulshooter that I can use to try to correct this, instead of using other app to mess display (I have nothing against them, but I won't support changes they can create)

But this would recquire some work on your side too before, to provide some information... as I obviously can't react to a bug I can't reproduce at home.
And I'm not even mentionning All-In-One commercial projects with Frontend (as source of erros)

**Comment by AckerApple** [comment]
Was just trying to get some keywords on a page that might help someone else. I will host the keywords and [directions needed here](https://github.com/AckerApple/megacade#-wild-west-shootout)

Maybe lastly you might consider a small one liner of: [If still having issues you may want to try solution posted here](https://github.com/AckerApple/megacade#-wild-west-shootout)

This issue can be closed
