### ISSUE TITLE
Device IDs change on different computers

### ISSUE THREAD

**Issue by Ctrl-LeftAlt-Delete** [argonlefou/DemulShooter#97]
Hi, I'm using a portable installation of DemulShooter with 2 light guns and noticed that part of the device names change from computer to computer.
Is it possible to enable partial device name matching in config.ini?

Example:
On one computer I get:
P1DeviceName = \\?\HID#VID_16C0&PID_0F01&MI_02&Col02#**8&1fff5996**&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
On the other one I get:
P1DeviceName = \\?\HID#VID_16C0&PID_0F01&MI_02&Col02#**9&c31b5c8**&0&0001#{378de44c-56ef-11d1-bc8c-00a0c91405dd}

The same happens with P2DeviceName. I highlighted the portions of the string that change.

I tired manually changing the config.ini to include the start of the string that stays the same but it did not help.
Is it possible to enable partial string matching, wildcards or regular expression matching for the device names?
Thank you for all the help and your awesome work with DemulShooter.  I've been using it for a very long time.

**Comment by argonlefou** [comment]
Hi,

Those strings are hardware-related : a part is coming from the device itself and will never change (like HID and VID) but some other parts are coming from the host computer/system (USB hub, motherboard hardware....or some other things that I don't know enough about to try to explain) and that's why you can have small changes between 2 different computers.

One one hand, I can't put some wildcards or regular expression for the user to fill-in the Player Device because it's not a text field where you can input something. And this will stay as it is (i.e : already filled list with found compatible devices)
And on the other hand, I can't use regular expression to match an user config-recorded string againts what is currently detected on the computer because there's no way to be 100% sure which part will not change. (By the way - in that case - this would be easier to just compare a part of the string...no need for regular expression)

But believe me, I tried at first to make things simpler. The current system is the conclusion of that....and there are still some devices out there that are changing those ID strings from time to time at each reboot.

So I'm affraid that changing your devices manually is still the best option, and the that can guarantee you no errors on that side.

But I'm surprised that putting the name in the .ini file directly would not work ? DemulShooter isn't doing anything more than storing the string so of you know it already you can just open the .ini file and write it without using the GUI (if the nameyou put yourselt is really correct)

**Comment by Ctrl-LeftAlt-Delete** [comment]
Hi, thank you very much for the explanation. Putting the device name in the
.ini file directly does work.
What I tried to do was put the first portion of the name that only contains
the HID and VID (the part that doesn't change) to see if DemulShooter would
match the first part of the string.
Is it possible to pass the config.ini as an option / parameter? That way I
could feed the appropriate config.ini depending on what computer I'm using.
That could even help if people wanted to use different virtual mouse
buttons.
Thanks again!

**Comment by argonlefou** [comment]
Well, a similar question as been answered not so long ago, for different "buttons profile" or "hardware profiles" on different games/computer.

The answer will be very simple : as there is a big chance that you're using batch or Ahk scripts or whatever frontend to run games and demulshooter......just add a small line in the script to copy the desired *ini file to demulshooter's folder before running it 
:)
